version: '3'

services:
  bi.webapi.ngtotalaccessapi.xtest:
    image: bi.webapi.ngtotalaccessapi.xtest:dev
    build:
      args:
        source: obj/Docker/empty/
    environment:
      - NUGET_PACKAGES=C:\.nuget\packages
      - NUGET_FALLBACK_PACKAGES=c:\.nuget\fallbackpackages
    volumes:
      - C:\Users\tharknes\Documents\GitHub\aspnetcore\NTTotalAccessAPINetCore\BI.WebApi.NGTotalAccessApi.xTest:C:\app
      - C:\Users\tharknes\onecoremsvsmon\15.0.26919.1:C:\remote_debugger:ro
      - C:\Users\tharknes\.nuget\packages\:C:\.nuget\packages:ro
      - C:\Program Files\dotnet\sdk\NuGetFallbackFolder:c:\.nuget\fallbackpackages:ro

    entrypoint: cmd /c "set DISABLE_PERFORMANCE_DEBUGGER=1 & C:\\remote_debugger\\x64\\msvsmon.exe /noauth /anyuser /silent /nostatus /noclrwarn /nosecuritywarn /nofirewallwarn /nowowwarn /timeout:2147483646"
    labels:
      com.microsoft.visualstudio.debuggee.program: "\"C:\\Program Files\\dotnet\\dotnet.exe\""
      com.microsoft.visualstudio.debuggee.arguments: " --additionalProbingPath c:\\.nuget\\packages --additionalProbingPath c:\\.nuget\\fallbackpackages  bin\\Debug\\netcoreapp2.0\\BI.WebApi.NGTotalAccessApi.xTest.dll"
      com.microsoft.visualstudio.debuggee.workingdirectory: "C:\\app"
      com.microsoft.visualstudio.debuggee.killprogram: "C:\\remote_debugger\\x64\\utils\\KillProcess.exe dotnet.exe"